### PR TITLE
various fixups; closes #14

### LINKED ISSUE #14: wrong start time in param_grid
If I start the simulation at 21000ya then I get the desired picture:
Screenshot from 2022-02-01 14-20-41

The problem was that in our tests we forgot to set the `START_TIME_AGO` parameter - so we simulated for 21000 years starting from 300 years ago (or something like that).

### PR DESCRIPTION
**Pull request by petrelharp**
I believe I found the problem - could you have a look at this, @giliapatterson ?

### CODE REVIEW

File: param_grid/make_param_grid.R [hunk 1]
```diff
@@ -1,34 +1,49 @@
...
+        P_D = 2^-c(1, 6),
+        YEAR_SHAPE = c(1, 2)
+    )
 
-# Parameter values that give number of simulated patches close to 250
-param_values <- data.frame(POP_SIZE = c(69.7, 310.8, 111.9),
-                           DISPERSAL_SIGMA = c(1.87, 0.28, 0.75),
-                           P_D = c(0.48, 0.26, 0.08),
-                           YEAR_SHAPE = c(1.95, 1.59, 1.26))
+    basedir <- "./post_500"
```
Comment (petrelharp) [inline param_grid/make_param_grid.R:23]: this way we can keep each experiment in it's own directory, and the code to set it up here
